### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by KuonjiAlice514** [zkawfanx/Atlantis#10]
想问一下作者大概训练了多少个epoch，花了多长时间？
我为了在2080TI（22G）上训练把train_batch_size设置成了1，一个epoch貌似要16个小时....
还有就是想问一下max_train_steps是总共只有30000step还是一个epoch有30000step

**Comment by zkawfanx** [comment]
如果我没记错的话，在3090上训练差不多需要10小时，batch size为2/4，accumulate gradients设为4，大概这样的设置。
max_train_steps=30000只是保留的diffusers example里的预设数值，一般在1w step以内就可以观察到sudden convergence现象，在之后可以根据需求停止训练的。

**Comment by KuonjiAlice514** [comment]
好的，非常感谢

**Comment by KuonjiAlice514** [comment]
还有一个问题，就是训练的时候设置的validation_image该如何选取？validation_prompt应该如何设置？能否将训练参数共享一下，非常感谢！

**Comment by zkawfanx** [comment]
validation image其实就是几张和训练depth同样格式的depth图片，然后你可以用之后完成训练时你想生成的prompt作为validation prompt进行验证，主要是用来观察是否训练是否收敛。训练参数和文件中的基本相同，区别可能就在于你使用的batch size更小一些。

**Comment by KuonjiAlice514** [comment]
虽然我已经把batch_size设置为1，但是我在使用UIEB数据集训练时总是爆显存，我感觉是因为有一些图像分辨率过大导致的，想问一下能否共享一下训练用的triplets用以复现论文结果

**Comment by zkawfanx** [comment]
你需要注意，训练时所有图像都是自动resize到512分辨率的，如果batch size为1仍然OOM的话，你可能需要显存更大的显卡才能训练。

**Comment by zkawfanx** [comment]
如果是显存在训练过程中逐渐增大一直到OOM的话，可能是训练过程中比如valid阶段的显存没有及时释放导致的，也许你可以提供一下报错信息以及你的训练log

**Comment by KuonjiAlice514** [comment]
有一张valid图像非常大，分辨率为1600*900，而且爆显存都是在valid阶段发生的，我换了一张小点的图就好了，感谢提醒

**Comment by KuonjiAlice514** [comment]
我在训练时为不爆显存将batch_size设置为1（未修改分辨率），训练3w个step之后没有收敛。于是我将batch_size重新设置为2后，为保证不爆显存将分辨率设置为448，训练到2w以上的step依旧不收敛。我是用的数据集是和论文中一样的UIEB数据集，按照git给出的流程生成triplets，训练指令只调整过分辨率，其他与git一致。训练loss曲线如图，想请作者给出一些帮助建议，谢谢！
![controlnet loss](https://github.com/user-attachments/assets/0ccc439e-66fa-496f-a28a-17f8d55bdba5)

**Comment by zkawfanx** [comment]
你给一些不同step时的validation生成结果看看，loss函数一般都是这样剧烈波动的，通过loss很难判断合适收敛

**Comment by KuonjiAlice514** [comment]
每隔5000step取了一个结果
![20000](https://github.com/user-attachments/assets/63dbfee0-8575-4cd5-9b97-4b0422a0931b)
![15000](https://github.com/user-attachments/assets/36546e26-7f40-447d-b7f2-cf129676d5cb)
![10000](https://github.com/user-attachments/assets/e16e502c-4770-4a9e-b12b-f2fb20cc50c4)
![5000](https://github.com/user-attachments/assets/490bd244-8bb6-4e29-9621-951cedb17fd6)

**Comment by zkawfanx** [comment]
Depth2Underwater controlnet的输入是depth，你可能用错了validation的输入了，你应该找一些陆地场景的depth结果作为valid image

**Comment by KuonjiAlice514** [comment]
感谢提醒，我重新训练一下

**Comment by KuonjiAlice514** [comment]
我把validation的输入改成depth之后训练了3w个step还是没有收敛，这是为什么呢？
![image](https://github.com/user-attachments/assets/6e112ae9-7838-4b35-9cc8-782705418944)
![image](https://github.com/user-attachments/assets/a426c3cf-035c-439a-8903-08a2f677e88b)

**Comment by zkawfanx** [comment]
看一下你准备的训练数据大概是什么样的，caption和validation是同一种格式嘛

**Comment by KuonjiAlice514** [comment]
![image](https://github.com/user-attachments/assets/02933e15-e1ce-47d0-982c-fa049f4b4f66)
![image](https://github.com/user-attachments/assets/008eaced-1c45-407d-b95a-bfa4e6413969)
![image](https://github.com/user-attachments/assets/bafe9e96-b96e-45f0-8077-0cde47e92a7a)
分别是深度图、原图、metadata
caption和validation是同一种格式是指metadata里面的句式要和validation一致吗？
我感觉训练的时候模型没有学到condition的信息，基本上就是跟着prompt在学习

**Comment by zkawfanx** [comment]
你的训练数据看起来倒是没什么问题，valid时候的prompt和metadata里不一致也可以，因为如果controlnet训练好了不管prompt给的啥，生成结果的layout应该都是和depth保持一致的。目前看训练数据这块你准备的应该是没有问题的。

再确认一下就是你的batch size是1对吧，gradient accumulation你是用了多少，也有可能是你的setting下收敛需要3w step以上，因为根据controlnet作者在repo discussion里提到的是batch size越大越有利于模型的收敛。

也许你可以把你训练的代码建个repo，我有空的时候clone下来看看本地跑能不能复现一下问题。

**Comment by KuonjiAlice514** [comment]
我batch_size设置的是2，显存不够所以调低了训练分辨率到448，gradient_accumulation设置的是4

**Comment by zkawfanx** [comment]
我想起来一个可能的问题，你需要check一下你保存的depth是8bit还是16bit的，在使用MiDaS或者Depth Anything保存深度文件的时候，记得将bit数从2调整为1。因为Diffusers库在处理png图片的时候会直接调用Image.convert('RGB')这样会直接将depth文件的数值截断，如果保存的是16bit的png的话，训练时的depth基本都是1.0的数值，所以会出现无法学习到depth condition的情况。

**Comment by KuonjiAlice514** [comment]
我没有修改bits那个参数，应该是用的16bit，我现在把bits改成1重新生成数据再训练试试

**Comment by KuonjiAlice514** [comment]
![image](https://github.com/user-attachments/assets/106a9f2f-bfa5-44a3-a456-c889e8e879ab)
这是使用修改后深度训练的结果，看起来效果很好了

**Comment by zkawfanx** [comment]
嗯，那应该没啥问题了
