### ISSUE TITLE
训练非常缓慢

### ISSUE THREAD

**Issue by codingCoderIsCodingNow** [zkawfanx/Atlantis#14]
我用的是4060Ti显卡，24GB显存，但是训练一轮（30000个it）需要30多天（600+h），是因为我用的Windows系统吗？我后面又开了个Linux子系统，还是没办法解决这个问题

**Comment by zkawfanx** [comment]
你搞错了吧，4060Ti哪儿来的24GB显存版本，应该是超显存了然后溢出的部分加载到内存里了，这会导致训练非常慢

**Comment by codingCoderIsCodingNow** [comment]
![image](https://github.com/user-attachments/assets/9fe30a10-8d6e-46ca-b21b-f7fdbbb0859b)
我这边任务管理器里显示的是这样的

**Comment by zkawfanx** [comment]
专用GPU内存8G才是你显卡的显存，共享GPU内存是从内存里借用的，但是用上这部分共享显存就会频繁从内存和GPU之间交换数据，导致训练非常慢

**Comment by codingCoderIsCodingNow** [comment]
明白了，感谢大佬
