### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ddz16** [zkawfanx/Atlantis#2]
Congratulations on the acceptance to CVPR. I want to know when will the code be made available?

**Comment by zkawfanx** [comment]
Thanks for your interest in our work. I assume to finish this by the end of next week if there is no other emergent tasks.

**Comment by ddz16** [comment]
Thank you for sharing the code. Do you have plans to release the dataset Atlantis you have generated (synthetic underwater images and depth maps) and the code for training the depth estimation model using this dataset?

**Comment by zkawfanx** [comment]
Yeah, we will release the dataset and trained controlnet soon. You can refer to the original repos of these methods for training code. I will also attach their links later.

**Comment by ddz16** [comment]
Thank you very much for your response. I did not find the code for training the depth estimation model in the MiDaS repo, so I am looking forward to seeing how you train MiDaS model.

**Comment by zkawfanx** [comment]
> Thank you very much for your response. I did not find the code for training the depth estimation model in the MiDaS repo, so I am looking forward to seeing how you train MiDaS model.

Unfortunately, MiDaS didn't release its training code until now. Recent _Depth Anything_ claims to implement the training code themselves but that they won't release the training code either.

I didn't retrain MiDaS in the paper, only using its pretrained model for depth prediction. Sorry but I can't help with the training code of MiDaS.

**Comment by ddz16** [comment]
Oh, I misunderstood before. MiDaS was not retrained, only iDisc and NeWCRFs were retrained on the Atlantis dataset. The trainging codes for iDisc and NeWCRFs are all I need.

**Comment by zkawfanx** [comment]
> Oh, I misunderstood before. MiDaS was not retrained, only iDisc and NeWCRFs were retrained on the Atlantis dataset. The trainging codes for iDisc and NeWCRFs are all I need.

Yeah, you're right. I have provided corresponding repo links down below, at the acknowledge part.

**Comment by ddz16** [comment]
These repo links are really useful. Do you have the plan to release pre-trained weights for iDisc and NeWCRFs (pre-trained on the Atlantis dataset)?

**Comment by zkawfanx** [comment]
Sorry but we didn't have such plan yet. It is a good suggestion and we will consider and work on it after the data release.

**Comment by ddz16** [comment]
Thank you for your reply and great work, I have no further questions.
