### ISSUE TITLE
Code and Data availablilty

### ISSUE THREAD

**Issue by 17Swagat** [zkawfanx/Atlantis#3]
Well...I read the paper and itss pretty cool tbh..  Well .. there are some stuff in the paper which I don't really understand due my lack of experience and have some doubts on.. which I intend to tackle later....
I was searching for the code-implementation and the datasets used and generated...
for my deep understanding and for experimenting... 
Just want to know will it be available and if yes when its likely to be released :)

**Comment by zkawfanx** [comment]
Hi, thanks for you appreciation on our work. It should be finished by last weekend but emmm... a lot of little things occupied my time. I will try my best to release them in 1~2 weeks. 

Sorry for the inconvenience. Stay tuned.
