### ISSUE TITLE
About format of the depth maps

### ISSUE THREAD

**Issue by Hryxyhe** [zkawfanx/Atlantis#5]
The generated depth conditioning image is in pfm format? But I fail to train the model using  pfm depth maps. Should I directly use the 8 bit png format depth maps?

**Comment by zkawfanx** [comment]
Yes, you should use the 8bit png format depth maps for training as the original SD + ControlNet does.

**Comment by Hryxyhe** [comment]
> Yes, you should use the 8bit png format depth maps for training as the original SD + ControlNet does.

Thanks for your response!
