### ISSUE TITLE
TypeError: CLIPTextModel.__init__() got an unexpected keyword argument 'variant'

### ISSUE THREAD

**Issue by LaibinChang** [zkawfanx/Atlantis#6]
![image](https://github.com/zkawfanx/Atlantis/assets/88143736/a03648cc-c40b-4d89-b760-370aa0548326)
My input is as follows:

export MODEL_DIR="runwayml/stable-diffusion-v1-5"
export OUTPUT_DIR="./depth2underwater"
CUDA_VISIBLE_DEVICES="2" accelerate launch train_controlnet.py \
--pretrained_model_name_or_path=$MODEL_DIR \
--output_dir=$OUTPUT_DIR \
--train_data_dir="./triplets"  \
--resolution=256 \
--learning_rate=1e-5 \
--validation_image "./120_img_.png" "./524_img_.png" \
--validation_prompt "an underwater view of a coral reef" "an angelfish swimming near an old ship" \
--train_batch_size=2 \
--gradient_accumulation_steps=4 \
--max_train_steps 30000

**Comment by zkawfanx** [comment]
It seems that diffusers of newer version adds the 'variant' argument for model initialization, what's your diffusers version? I will check this later.

**Comment by LaibinChang** [comment]
> It seems that diffusers of newer version adds the 'variant' argument for model initialization, what's your diffusers version? I will check this later.

My diffusers version is the latest [0.28.0], and I have solved this issue by revising transformers vesion from 4.26.1 to 4.27.0. Thank you for your response.
