### ISSUE TITLE
ControlNet Weights&Datasets

### ISSUE THREAD

**Issue by Sticker-Sjh** [zkawfanx/Atlantis#7]
第二步的control net可以不训练吗，用你的权重如果你愿意上传的话

第三步推理的controlnet path指的是第二步训练好的权重文件吗

**Comment by zkawfanx** [comment]
1. 权重和数据集我过几天有空会一起上传。
2. controlnet path指的就是训练好的权重。

**Comment by Sticker-Sjh** [comment]
感谢作者回复，很棒的工作，期待你的上传
1️⃣我可以理解为controlnet是用水下的数据集训练出来的，最后推理仅使用陆地的深度图（重新用MiDaS）和caption（Blipv2）就可以生成不存在的逼真水下图像吗
2️⃣然后关于生成深度图我看提到新的深度估计模型depth anything也可以是不
3️⃣最后训练controlnet这个命令应该在终端输入么
4️⃣one more 我一开始就用的最新的diffusers还用在训练controlnet的时候重新clone一个吗，应该不用了吧。

zkawfanx ***@***.***>于2024年6月12日 周三20:56写道：

**Comment by zkawfanx** [comment]
1. 是的，controlnet利用underwater图像和估计的depth进行训练，学习深度图作为输入并结合文本的描述生成水下纹理的能力，然后利用陆地深度结合文本描述，即可生成此前不存在的水下场景图像。
2. 生成的深度图不局限与midas，depth anything也可以使用。
3. 这个我没太理解你的意思，如果你说的是运行时的脚本，是在终端输入。
4. 不用，能正常运行就行。

**Comment by Sticker-Sjh** [comment]
![image](https://github.com/zkawfanx/Atlantis/assets/140473235/818e4316-eb7f-4d60-8e26-5b3811f01978)
训练controlnet，参数不对，我没有安装wsl，所以就只能改了训练参数与训练模型的路径，是因为没有export的原因吗

**Comment by zkawfanx** [comment]
报错的是没有调用该路径参数，你可以调试下argparse这部分的代码，打印一下看看实际存在哪些参数

**Comment by Sticker-Sjh** [comment]
好的多谢，这个validation image和prompt没看懂他俩具体是啥意思，参数设置里面也没有他俩

zkawfanx ***@***.***>于2024年6月13日 周四18:01写道：

**Comment by zkawfanx** [comment]
这俩主要就是在每轮训练之后用图片和文本生成若干结果图，用于观察某个阶段的突然收敛用的，这个应该是默认参数，你再找找

**Comment by Sticker-Sjh** [comment]
好的收到我以为是训练开始时要改的参数
这个controlnet可以理解成风格迁移模型吗，只不过这个风格可以先学习，然后再转化

zkawfanx ***@***.***>于2024年6月13日 周四18:46写道：

**Comment by zkawfanx** [comment]
可以简单看作风格迁移相似的功能，Stable Diffusion主要得益于图像与文本的特征对齐，可以生成文本描述的场景内容，而controlnet则在于提供可控生成的一种机制，从而生成符合depth场景结构的水下内容

**Comment by Sticker-Sjh** [comment]
> 可以简单看作风格迁移相似的功能，Stable Diffusion主要得益于图像与文本的特征对齐，可以生成文本描述的场景内容，而controlnet则在于提供可控生成的一种机制，从而生成符合depth场景结构的水下内容

my dear author，有空可以先传一下control net的训练权重嘛，我先推理一下试试，我还是不能成功自己训练control net准备着装个Ubuntu了。我是准备用这个做一个高质量的数据集生成，虽然还不知道能否成功，想问一下这个输出照片和输入照片的尺寸不会发生变化吧，因为我不是做深度估计的，我不想再重新打标签了🫡

**Comment by zkawfanx** [comment]
我有空尽快上传吧，因为最近CVPR准备开会了，可能还需要忙几天

**Comment by Sticker-Sjh** [comment]
好滴好滴，关于自己训练controlnet还有么有其他的建议您可以给我的

zkawfanx ***@***.***>于2024年6月14日 周五15:55写道：

**Comment by zkawfanx** [comment]
你可以看看ControlNet的repo，里面有discussion和documentation等不错的经验

**Comment by Sticker-Sjh** [comment]
收到，祝顺利

zkawfanx ***@***.***>于2024年6月14日 周五15:59写道：
