### ISSUE TITLE
SQUID dataset

### ISSUE THREAD

**Issue by ddz16** [zkawfanx/Atlantis#8]
作者您好，SQUID数据集的官方网站（ https://csms.haifa.ac.il/profiles/tTreibitz/datasets/ambient_forwardlooking/index.html ）好像挂了，这个网站貌似在以色列，现在网上也没有该数据集的资源。请问能提供您下载好的SQUID资源吗，用网盘之类的。

**Comment by zkawfanx** [comment]
我没有分发数据集的权限，你可以邮件联系作者，之前sea-thru挂了我邮件询问后他们传了kaggle，你也可以询问一下

**Comment by ddz16** [comment]
谢谢，我去找作者问下
