### ISSUE TITLE
control net 训练

### ISSUE THREAD

**Issue by Sticker-Sjh** [zkawfanx/Atlantis#9]
自己现在训练了controlnet，但是自己训练的权重生成出来的内容，会把原图片内容都会改变，而不像你给出 的权重那样保持原图中的内容不变，可以给出更多训练controlnet的细节么，除了官方的一些intro，万分感谢

**Comment by zkawfanx** [comment]
你可以贴一些实例给我看看么，可能是你的模型还没有训练到突然收敛阶段

**Comment by Sticker-Sjh** [comment]
[config.json](https://github.com/user-attachments/files/16063789/config.json)
你可以给个邮箱或者wx么，我发训练log文件给你

**Comment by zkawfanx** [comment]
这个文件是controlnet默认的参数文件，你可以看见release里的config文件跟你发的这个是一样的。
邮件你发zkawfanx@gmail.com吧
